'use strict';
const API_URL='https://script.google.com/macros/s/AKfycbwjECihD-JQg6ITpewj4ga3HzMraB4sUNhrCf40l6Fjlf2EOhIY9oMknFHAnG_XTCPP/exec';
const SESSION_KEY='haftalikBakimV530User';const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active')}
function message(t,type=''){const x=$('loginMessage');x.textContent=t;x.className='message '+type}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2400)}
function jsonp(action,params={}){return new Promise((resolve,reject)=>{const cb='cmms_'+Date.now()+'_'+Math.floor(Math.random()*99999),s=document.createElement('script');let done=false;const clean=()=>{delete window[cb];if(s.parentNode)s.remove()};const timer=setTimeout(()=>{if(done)return;done=true;clean();reject(new Error('Bağlantı zaman aşımına uğradı.'))},15000);window[cb]=d=>{if(done)return;done=true;clearTimeout(timer);clean();resolve(d)};s.onerror=()=>{if(done)return;done=true;clearTimeout(timer);clean();reject(new Error('Apps Script bağlantısı kurulamadı.'))};s.src=API_URL+'?'+new URLSearchParams({action,callback:cb,_:Date.now(),...params});document.head.appendChild(s)})}
async function testApi(){message('Bağlantı test ediliyor...');try{const r=await jsonp('health');$('debugOutput').textContent=JSON.stringify(r,null,2);if(!r.success)throw Error(r.message);message('Bağlantı başarılı. Sürüm: '+r.version,'success')}catch(e){message(e.message,'error')}}
async function login(){const password=$('password').value.trim();if(!password)return message('Şifre giriniz.','error');$('loginBtn').disabled=true;try{const r=await jsonp('login',{password});$('debugOutput').textContent=JSON.stringify(r,null,2);if(!r.success||!r.user)throw Error(r.message||'Giriş başarısız');sessionStorage.setItem(SESSION_KEY,JSON.stringify(r.user));openHome(r.user)}catch(e){message(e.message,'error')}finally{$('loginBtn').disabled=false}}
function openHome(u){$('welcome').textContent='Hoş geldiniz, '+u.operator;$('role').textContent=u.role||'teknisyen';$('email').textContent=u.email||'-';$('adminBtn').classList.toggle('hidden',!String(u.role||'').toLocaleLowerCase('tr-TR').includes('admin'));$('logoutBtn').classList.remove('hidden');show('homeView')}
function logout(){sessionStorage.removeItem(SESSION_KEY);$('logoutBtn').classList.add('hidden');$('password').value='';show('loginView')}
$('loginBtn').onclick=login;$('apiTestBtn').onclick=testApi;$('logoutBtn').onclick=logout;$('password').onkeydown=e=>{if(e.key==='Enter')login()};$('adminBtn').onclick=()=>location.href='admin-maintenance.html';$('maintenanceBtn').onclick=()=>location.href='weekly-maintenance.html';$('qrBtn').onclick=()=>location.href='weekly-maintenance.html';try{const u=JSON.parse(sessionStorage.getItem(SESSION_KEY));if(u?.operator)openHome(u)}catch(e){}
