'use strict';
const CFG={SPREADSHEET_ID:'1J-4mdyEHUpytO7RNjp2q3dR6xCOszTGTpaWuN-MpxiQ',USER:'veri',MACHINES:'mak-list',TEMPLATES:'weeklyMaintenanceTemplates',FOLDER:'Haftalik_Bakim_Referans_Resimleri',VERSION:'5.3.6'};
const HEADERS=['TemplateID','MachineID','MachineName','CostCenter','Region','System','Part','Task','TargetValue','OrderNo','PhotoRequired','ReferenceImageUrl','ReferenceImageName','ReferenceImageDriveId','Active','CreatedAt','UpdatedAt'];
function doGet(e){const cb=e&&e.parameter?e.parameter.callback:'';try{const a=norm_(e&&e.parameter?e.parameter.action:'health');let r;if(!a||a==='health')r=health_();else if(a==='login')r=login_(e.parameter.password);else if(a==='listmachines')r=listMachines_();else if(a==='listmaintenancetemplates')r=listTemplates_(e.parameter.machineId||'');else if(a==='updatemaintenancetemplate')r=updateTemplate_(e.parameter.payload);else if(a==='deletemaintenancetemplate')r=deleteTemplate_(e.parameter.templateId);else r={success:false,message:'Geçersiz işlem: '+a};return response_(r,cb)}catch(x){return response_({success:false,message:x.message||'Sistem hatası'},cb)}}
function doPost(e){try{if(norm_(e.parameter.action)!=='createmaintenancetemplatewithimage')return iframe_({success:false,message:'Geçersiz işlem'});return iframe_(createWithImage_(e.parameter))}catch(x){return iframe_({success:false,message:x.message||'Sistem hatası'})}}
function health_(){return{success:true,application:'Haftalık Bakım CMMS',version:CFG.VERSION,status:'ACTIVE',machineRows:table_(sheet_(CFG.MACHINES)).rows.length,templateRows:table_(templateSheet_()).rows.length}}
function login_(password){const p=String(password||'').trim(),t=table_(sheet_(CFG.USER)),h=t.headers.map(canon_),name=col_(h,['op isimleri','op isileri','operator','operator adi']),pin=col_(h,['sifre','pin']),role=col_(h,['yetki','rol']),mail=col_(h,['mail adresi','mail','eposta']);if(name<0||pin<0||role<0)throw Error('veri sayfası başlıkları eksik');for(const row of t.rows)if(String(row[pin]||'').trim()===p)return{success:true,user:{operator:String(row[name]||''),role:String(row[role]||''),email:mail<0?'':String(row[mail]||'')}};return{success:false,message:'Şifre hatalı veya kullanıcı bulunamadı.'}}
function listMachines_(){const t=table_(sheet_(CFG.MACHINES)),h=t.headers.map(canon_),id=col_(h,['id','makine id']),name=col_(h,['makine adi']),cost=col_(h,['maliyet mer','maliyet merkezi']);if(id<0||name<0||cost<0)throw Error('mak-list başlıkları eksik');const machines=t.rows.map(r=>({id:String(r[id]||'').trim(),machineName:String(r[name]||'').trim(),costCenter:String(r[cost]||'').trim()})).filter(x=>x.id&&x.machineName);machines.sort((a,b)=>a.machineName.localeCompare(b.machineName,'tr'));return{success:true,count:machines.length,machines}}
function createWithImage_(p){if(!p.payload||!p.imageBase64)throw Error('Referans resim zorunludur.');const d=JSON.parse(p.payload),machine=listMachines_().machines.find(x=>x.id===String(d.machineId||'').trim());if(!machine)throw Error('Makine mak-list sayfasında bulunamadı.');if(!String(d.region||'').trim()||!String(d.system||'').trim()||!String(d.task||'').trim())throw Error('Bölge, sistem ve bakım zorunludur.');const lock=LockService.getScriptLock();lock.waitLock(20000);try{const sh=templateSheet_(),existing=table_(sh).rows.map(r=>obj_(table_(sh).headers,r)).find(x=>String(x.MachineID||'')===machine.id&&norm_(x.Task)===norm_(d.task)&&yes_(x.Active));if(existing)throw Error('Aynı aktif bakım maddesi zaten mevcut.');const blob=Utilities.newBlob(Utilities.base64Decode(p.imageBase64),p.imageType||'image/jpeg',p.imageName||'referans.jpg'),file=folder_().createFile(blob);file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW);const url='https://drive.google.com/uc?export=view&id='+file.getId(),templateId='TMP-'+Utilities.getUuid().substring(0,8).toUpperCase();append_(sh,{TemplateID:templateId,MachineID:machine.id,MachineName:machine.machineName,CostCenter:machine.costCenter,Region:String(d.region).trim(),System:String(d.system).trim(),Part:String(d.part||'').trim(),Task:String(d.task).trim(),TargetValue:String(d.targetValue||'').trim(),OrderNo:Number(d.orderNo)||1,PhotoRequired:d.photoRequired?'EVET':'HAYIR',ReferenceImageUrl:url,ReferenceImageName:file.getName(),ReferenceImageDriveId:file.getId(),Active:d.active!==false?'EVET':'HAYIR',CreatedAt:new Date(),UpdatedAt:new Date()});return{success:true,source:'CMMS_APPS_SCRIPT',templateId,referenceImageUrl:url}}finally{lock.releaseLock()}}
function listTemplates_(machineId){const t=table_(templateSheet_());let templates=t.rows.map(r=>{const o=obj_(t.headers,r);return{templateId:o.TemplateID,machineId:o.MachineID,machineName:o.MachineName,costCenter:o.CostCenter,region:o.Region,system:o.System,part:o.Part,task:o.Task,targetValue:o.TargetValue,orderNo:Number(o.OrderNo||1),photoRequired:yes_(o.PhotoRequired),referenceImageUrl:driveDisplayUrl_(o.ReferenceImageDriveId,o.ReferenceImageUrl||o.ReferenceImage||''),referenceImageOriginalUrl:o.ReferenceImageUrl||o.ReferenceImage||'',referenceImageName:o.ReferenceImageName||'',referenceImageDriveId:o.ReferenceImageDriveId||'',active:yes_(o.Active)}});if(machineId)templates=templates.filter(x=>x.machineId===machineId);templates.sort((a,b)=>a.orderNo-b.orderNo);return{success:true,count:templates.length,templates}}
function templateSheet_(){const ss=SpreadsheetApp.openById(CFG.SPREADSHEET_ID);let sh=ss.getSheetByName(CFG.TEMPLATES);if(!sh){sh=ss.insertSheet(CFG.TEMPLATES);sh.getRange(1,1,1,HEADERS.length).setValues([HEADERS]);sh.setFrozenRows(1)}else{const headers=sh.getRange(1,1,1,Math.max(1,sh.getLastColumn())).getDisplayValues()[0].map(String);const old=headers.indexOf('ReferenceImag');if(old>=0&&!headers.includes('ReferenceImageUrl')){sh.getRange(1,old+1).setValue('ReferenceImageUrl');headers[old]='ReferenceImageUrl'}HEADERS.forEach(h=>{if(!headers.includes(h)){sh.getRange(1,sh.getLastColumn()+1).setValue(h);headers.push(h)}})}return sh}
function updateTemplate_(payload){
  if(!payload)throw Error('Güncelleme verisi bulunamadı.');
  const d=typeof payload==='string'?JSON.parse(payload):payload;
  const templateId=String(d.templateId||'').trim();
  if(!templateId)throw Error('TemplateID zorunludur.');
  const machine=listMachines_().machines.find(x=>x.id===String(d.machineId||'').trim());
  if(!machine)throw Error('Makine mak-list sayfasında bulunamadı.');
  if(!String(d.region||'').trim()||!String(d.system||'').trim()||!String(d.task||'').trim())throw Error('Bölge, sistem ve bakım zorunludur.');
  const sh=templateSheet_(),t=table_(sh),idCol=t.headers.indexOf('TemplateID'),rowIndex=t.rows.findIndex(row=>String(row[idCol]||'').trim()===templateId);
  if(rowIndex<0)throw Error('Bakım tanımı bulunamadı.');
  const duplicate=t.rows.some((row,i)=>i!==rowIndex&&String(row[t.headers.indexOf('MachineID')]||'').trim()===machine.id&&norm_(row[t.headers.indexOf('Task')])===norm_(d.task)&&yes_(row[t.headers.indexOf('Active')]));
  if(duplicate)throw Error('Aynı makinede aynı aktif bakım maddesi zaten mevcut.');
  updateRow_(sh,t.headers,rowIndex+2,{MachineID:machine.id,MachineName:machine.machineName,CostCenter:machine.costCenter,Region:String(d.region).trim(),System:String(d.system).trim(),Part:String(d.part||'').trim(),Task:String(d.task).trim(),TargetValue:String(d.targetValue||'').trim(),OrderNo:Number(d.orderNo)||1,PhotoRequired:d.photoRequired?'EVET':'HAYIR',Active:d.active===false?'HAYIR':'EVET',UpdatedAt:new Date()});
  return{success:true,templateId,message:'Bakım tanımı güncellendi.'};
}
function deleteTemplate_(templateId){
  const id=String(templateId||'').trim();if(!id)throw Error('TemplateID zorunludur.');
  const sh=templateSheet_(),t=table_(sh),idCol=t.headers.indexOf('TemplateID'),rowIndex=t.rows.findIndex(row=>String(row[idCol]||'').trim()===id);
  if(rowIndex<0)throw Error('Bakım tanımı bulunamadı.');
  sh.deleteRow(rowIndex+2);
  return{success:true,templateId:id,message:'Bakım tanımı silindi.'};
}
function updateRow_(sh,headers,rowNo,updates){
  const values=sh.getRange(rowNo,1,1,headers.length).getValues()[0];
  Object.keys(updates).forEach(key=>{const i=headers.indexOf(key);if(i>=0)values[i]=updates[key]});
  sh.getRange(rowNo,1,1,headers.length).setValues([values]);
}
function driveDisplayUrl_(driveId,storedUrl){const id=String(driveId||'').trim()||extractDriveId_(storedUrl);return id?'https://drive.google.com/thumbnail?id='+encodeURIComponent(id)+'&sz=w1600':String(storedUrl||'')}function extractDriveId_(url){const text=String(url||'');const match=text.match(/[?&]id=([^&]+)/)||text.match(/\/d\/([^/]+)/);return match?match[1]:''}
function folder_(){const it=DriveApp.getFoldersByName(CFG.FOLDER);return it.hasNext()?it.next():DriveApp.createFolder(CFG.FOLDER)}function sheet_(n){const s=SpreadsheetApp.openById(CFG.SPREADSHEET_ID).getSheetByName(n);if(!s)throw Error(n+' sayfası bulunamadı');return s}function table_(s){const r=s.getLastRow(),c=s.getLastColumn();if(r<1||c<1)return{headers:[],rows:[]};const v=s.getRange(1,1,r,c).getDisplayValues();return{headers:v[0].map(x=>String(x).trim()),rows:v.slice(1).filter(row=>row.some(x=>String(x).trim()))}}function append_(s,o){const h=s.getRange(1,1,1,s.getLastColumn()).getDisplayValues()[0];s.appendRow(h.map(x=>Object.prototype.hasOwnProperty.call(o,x)?o[x]:''))}function obj_(h,r){const o={};h.forEach((x,i)=>o[x]=r[i]);return o}function col_(h,a){for(const x of a){const i=h.indexOf(canon_(x));if(i>=0)return i}return-1}function canon_(v){return String(v||'').trim().toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,' ').trim()}function norm_(v){return canon_(v)}function yes_(v){return v===true||['evet','aktif','true','1'].includes(norm_(v))}function response_(d,cb){const j=JSON.stringify(d),ok=/^[A-Za-z_$][\w$]*$/.test(String(cb||''));return ContentService.createTextOutput(ok?cb+'('+j+');':j).setMimeType(ok?ContentService.MimeType.JAVASCRIPT:ContentService.MimeType.JSON)}function iframe_(d){d.source='CMMS_APPS_SCRIPT';return HtmlService.createHtmlOutput('<script>parent.postMessage('+JSON.stringify(d)+',"*");</script><p>İşlem tamamlandı.</p>')}
function testHealth(){Logger.log(JSON.stringify(health_(),null,2))}function testLoginEngin11(){Logger.log(JSON.stringify(login_('11'),null,2))}function testListMachines(){Logger.log(JSON.stringify(listMachines_(),null,2))}function testListMaintenanceTemplates(){Logger.log(JSON.stringify(listTemplates_(''),null,2))}
